### ISSUE TITLE
Bayern Holidays are not showing up!

### ISSUE THREAD

**Issue by hbfard** [Luzifer/go-holidays#1]
I am sending the following request to your backend: https://holiday-api.fyi/de-by/2022
and I have noticed that Bayern Holidays are not included in public holidays result. 
For example: Aug 15, Sep 20, Oct 31
Any quick fix possible?

**Comment by Luzifer** [comment]
- August 15 "Mariä Himmelfahrt" was mistaken with "Christi Himmelfahrt", will be fixed soon (https://github.com/Luzifer/go-holidays/commit/9e3382f215668c9487b0aa823263a790b9ec35f6)
- September 20 "Weltkindertag" is only a holiday in Thüringen (`de-th`)
- October 31 "Reformationstag" is not a holiday in Bayern, only in `bb, hb, hh, mv, ni, sh, sn, st, th`

At least that's the information I found… Do you have other sources?

**Comment by hbfard** [comment]
Oh yeah,It is only 15th of Aug. u r right.Thanks a lot for the reply and the upcoming fix.
Cheers,Hooman


Sent from Yahoo Mail for iPhone


On Thursday, August 18, 2022, 1:43 PM, Knut Ahlers ***@***.***> wrote:



   
   - August 15 "Mariä Himmelfahrt" was mistaken with "Christi Himmelfahrt", will be fixed soon
   - September 20 "Weltkindertag" is only a holiday in Thüringen (de-th)
   - October 31 "Reformationstag" is not a holiday in Bayern, only in bb, hb, hh, mv, ni, sh, sn, st, th

At least that's the information I found… Do you have other sources?

**Comment by Luzifer** [comment]
Fixed in https://github.com/Luzifer/go-holidays/releases/tag/v0.4.0
